### ISSUE TITLE
Many gmh5225 links are just forks

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [gmh5225/awesome-game-security#4]
A very large amount of the links on this list are forks with no updates over the original repository. This is bad because:
1. the link will not contain the most up-to-date version of the repository;
2. this essentially steals credit from the original author, making it appear as if the person who forked the repo created it.

Please change the links in this repository to point to the original repositories instead, unless the fork adds some useful changes.

**Comment by gmh5225** [comment]
This is mainly a fork operation to ensure that the original project is not deleted

**Comment by gmh5225** [comment]
If you want to go to the original project, then just jump straight to it yourself

**Comment by HoLLy-HaCKeR** [comment]
You can fork the repository and keep the original link in this list, and then when the original repository gets removed you can update the link to your repo.

**Comment by gmh5225** [comment]
Good idea, I will do that afterwards, thanks for the advice

**Comment by HoLLy-HaCKeR** [comment]
I am currently writing a script to update the links, I will create a pull request when it's done.

**Comment by gmh5225** [comment]
Wow, amazing work

**Comment by ZeaMays14142** [comment]
> Good idea, I will do that afterwards, thanks for the advice

Finally i found a way to reach you.
I want to really thank you for your endless forking work, as this branching system saved LoopHPCs, which i could not find anywhere, after reading the source paper (which in itself is incredibly interesting) and not finding the code nor contacts for any of the authors.
Again, thank you.
You helped archive some wonderfully interesting work.
By any chance, do you have any knowledge of why was the original https://github.com/binlinc/LoopHPCs USENIX repo deleted?
Also, how does this wonderful archiving via branching works? is there a main link with all the forks?

**Comment by gmh5225** [comment]
> > Good idea, I will do that afterwards, thanks for the advice好主意，我以后会这样做，谢谢你的建议
> 
> Sorry for the necro, i could not find a way to contact you otherwise对不起，死灵，我找不到其他方式与您联系
> 
> Finally i found a way to reach you.最后，我找到了联系你的方法。 I want to really thank you for your endless forking work, as this branching system saved LoopHPCs, which i could not find anywhere, after reading the source paper (which in itself is incredibly interesting) and not finding the code nor contacts for any of the authors.我真的要感谢你无休止的分叉工作，因为这个分支系统保存了 LoopHPC，在阅读了源论文（这本身非常有趣）之后，我在任何地方都找不到它，并且没有找到任何作者的代码或联系人。 Again, thank you. 再次感谢大家。 You helped archive some wonderfully interesting work.你帮助存档了一些非常有趣的工作。 By any chance, do you have any knowledge of why was the original https://github.com/binlinc/LoopHPCs USENIX repo deleted?无论如何，您是否知道为什么删除了原始 https://github.com/binlinc/LoopHPCs USENIX 存储库？ Also, how does this wonderful archiving via branching works? is there a main link with all the forks?另外，这种通过分支进行的精彩存档是如何工作的？所有分叉都有主链接吗？

I'm glad you're interested in my work. I'm not quite sure why the author deleted it, I just forked it.

**Comment by a2102107** [comment]
Thank you for your email. I appreciate your patience as I am currently swamped with work and unable to respond immediately. Please allow me a moment to address your inquiry or concern as soon as I can.




---Original---
From: ***@***.***&gt;
Date: Tue, Jan 30, 2024 09:07 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [gmh5225/awesome-game-security] Many gmh5225 links are just forks(Issue #4)




   
Good idea, I will do that afterwards, thanks for the advice好主意，我以后会这样做，谢谢你的建议
  
Sorry for the necro, i could not find a way to contact you otherwise对不起，死灵，我找不到其他方式与您联系
 
Finally i found a way to reach you.最后，我找到了联系你的方法。 I want to really thank you for your endless forking work, as this branching system saved LoopHPCs, which i could not find anywhere, after reading the source paper (which in itself is incredibly interesting) and not finding the code nor contacts for any of the authors.我真的要感谢你无休止的分叉工作，因为这个分支系统保存了 LoopHPC，在阅读了源论文（这本身非常有趣）之后，我在任何地方都找不到它，并且没有找到任何作者的代码或联系人。 Again, thank you.&nbsp;再次感谢大家。 You helped archive some wonderfully interesting work.你帮助存档了一些非常有趣的工作。 By any chance, do you have any knowledge of why was the original https://github.com/binlinc/LoopHPCs USENIX repo deleted?无论如何，您是否知道为什么删除了原始 https://github.com/binlinc/LoopHPCs USENIX 存储库？ Also, how does this wonderful archiving via branching works? is there a main link with all the forks?另外，这种通过分支进行的精彩存档是如何工作的？所有分叉都有主链接吗？
  
I'm glad you're interested in my work. I'm not quite sure why the author deleted it, I just forked it.

**Comment by gmh5225** [comment]
I'm glad you're interested in my work. I'm not quite sure why the author deleted it, I just forked it.
